apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: preeti097/authorisation
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: preeti097/employee
      context: employee
      docker:
        dockerfile: Dockerfile
        # noCache: true
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: preeti097/project
      context: project
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .